services:
  backend:
    image: sysid/backend
    build: ./backend
    command: ["fastapi", "dev", "server.py", "--port", "8000"]
    volumes:
      - ./backend/step_input/models:/app/step_input/models
      - ./backend/osc_input/models:/app/osc_input/models
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend:
    image: sysid/frontend
    build: ./frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
